#!/usr/bin/env python3

import ncplugin
import NCrystal as NC
import numpy as np
import matplotlib.pyplot as plt

physmodel = ncplugin.PhysicsModel( sigma=2.0, lambda_cutoff=5.0 )

print('cross section @   3.0 Aa : %g barn'%physmodel.calcCrossSection(NC.wl2ekin(3.0)) )
print('cross section @   7.0 Aa : %g barn'%physmodel.calcCrossSection(NC.wl2ekin(7.0)) )
print('cross section @   0.5 eV : %g barn'%physmodel.calcCrossSection( 0.5 ) )
print('cross section @ 0.001 eV : %g barn'%physmodel.calcCrossSection( 0.001 ) )

wls = np.linspace(0.01,10.0,1000)
plt.plot( wls, physmodel.calcCrossSection(NC.wl2ekin(wls)) )
plt.xlabel('angstrom')
plt.ylabel('barn')
plt.show()
