
//Define exported symbols used by NCrystal to activate the plugin. This is
//mostly generic, except for the registerPlugin function which can potentially
//be modified in some use-cases.

#define NCPLUGIN_BOILERPLATE_CC
#include "NCrystal/NCPluginBoilerplate.hh"

#include "NCPluginFactory.hh"


namespace NCPluginNamespace {

  //Temporary stuff for data file registration - should be simplified once https://github.com/mctools/ncrystal/issues/56 gets resolved...

  //Fwd declared data file registration function. It is defined in
  //NCPluginData.cc, a file which was (apart from a few lines at the top) was
  //generated by the command:
  //
  //  ncrystal_ncmat2cpp --full -v --name NCPluginNamespace::registerData testcode/data/nanodiamond_SANSND.ncmat -o src/NCPluginData.cc
  //
  void registerData();

}

void NCP::registerPlugin()
{
  //This function is required for the plugin to work. It should register factories (or
  //potentially other stuff, e.g. adding in-mem data files, etc.) for the
  //plugin.
  NC::registerFactory(std::make_unique<NCP::PluginFactory>());

  //Register data files defined in NCPluginData.cc:
  registerData();
};
